apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z4wpd97r1-python 
  janus-idp.io/tekton: z4wpd97r1-python
  backstage.io/kubernetes-id: z4wpd97r1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z4wpd97r1-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml